stages:
  - check
  - docs
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: FULL

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - cargo/
  - target/

build_and_test:
  stage: check
  image: rust:1.65-slim-bullseye
  before_script:
    - apt-get update
    - apt-get install -y python3-dev
  script:
    - cargo build
    - cargo test

build_py_37:
  stage: check
  image: rust:1.65-slim-buster
  before_script:
    - apt-get update
    - apt-get install -y python3.7-dev python3-pip
    - pip3 install maturin
  script:
    - cargo build
    - cargo test
    - cd py-tritium-remote && maturin build --interpreter python3.7
  artifacts:
    paths:
      - target/wheels

build_py_39:
  stage: check
  image: rust:1.65-slim-bullseye
  before_script:
    - apt-get update
    - apt-get install -y python3.9-dev python3-pip
    - pip3 install maturin
  script:
    - cargo build
    - cargo test
    - cd py-tritium-remote && maturin build build --interpreter python3.9
  artifacts:
    paths:
      - target/wheels

fmt_rust:
  stage: check
  image: rust:1.65-slim-buster
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check

fmt_py:
  stage: check
  image: python:3.11.0-alpine3.15
  before_script:
    - pip install black
  script:
      # We have to specify files with no extension exactly
    - black --check .

docs_rust:
  stage: docs
  image: rust:1.65-slim-buster
  dependencies: []
  needs: []
  before_script:
    - rustup component add rustfmt
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
