stages:
  - check
  - docs
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: FULL

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - cargo/
  - target/

build_and_test_rust:
  stage: check
  image: rust:1.65-slim-buster
  before_script:
    - apt-get update
    - apt-get install -y python3-dev
  script:
    - cargo build
    - cargo test

fmt_rust:
  stage: check
  image: rust:1.65-slim-buster
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check

docs_rust:
  stage: docs
  image: rust:1.65-slim-buster
  dependencies: []
  needs: []
  before_script:
    - rustup component add rustfmt
  script:
    - cargo doc -p tritium_remote
  artifacts:
    paths:
      - target/doc

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
