stages:
  - check
  - deploy

build_and_test_rust:
  stage: check
  image: rust:1.65-buster-slim
  script:
    - cargo build
    - cargo test

check_rust:
  stage: check
  image: rust:1.65-buster-slim
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
