[workspace]
members = [
    "tritium-remote", 
    "mock-tritium-gateway", 
    "py-tritium-remote", 
    "tritium-remote/examples/system_info", 
    "tritium-remote/examples/start_script", 
    "tritium-remote/examples/play_sequence"
]
