[package]
name = "tritium_remote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "*"
tungstenite = { version = "*" }
# async-tungstenite = { version = "*", features=["tokio-runtime"] }
tokio-tungstenite = '*'
futures = "*"
futures-util = "*"
thiserror = "1"